services:
  widget:
    container_name: widget
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    env_file: "widget/.env"
    ports:
      - "4000:4000"